### ISSUE TITLE
Services doesn't start

### ISSUE THREAD

**Issue by thiras** [debops/ansible-elastic_co#1]
With current playbook, none of the elastic_co services start by default. It should be done by manually. They should start automatically instead.

**Comment by drybjed** [comment]
This role only manages the Elastic APT repositories and installs the packages. You are supposed to use the [`debops.elasticsearch`](https://github.com/debops/ansible-elasticsearch/) and/or [`debops.kibana`](https://github.com/debops/ansible-kibana/) roles to configure and start the services. Each role contains and example playbook you can use.

**Comment by thiras** [comment]
Thanks. I guess readme documentation is a bit unclear. I will try my best to update it.

**Comment by drybjed** [comment]
Closing this issue as resolved.
